# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 78f247e6fb9e0989e24f30fd03c5b5eb87c0d8bde3efb419a74d27fbb94c009dd20bb0ffcccf8e373c2e58257c609f39e2735fe2413b820daa8b57c8f5f5bb9a

test:
  secret_key_base: 3940b2e1e2a4f66c2e34c6c656b0883c8a71c0bf089f6f42f4c64278fd2de4f98cf00788bfcdb3e68e04c2abd0657f4cdfb7ef6b370219e1de41bdc032fc7f9e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
